// Writes functions/hqCrew.json: each crew seat's brief (src/hqOrg.js
// agentBrief), room, title and connectors, for the HQ's in-app chat
// (functions/hqChat.js). Functions can't import the app's modules, so this is
// the mirror, and scripts/test-hq-chat.mjs fails the moment it goes stale.
//
// Run after changing a seat in hqOrg.js:  npm run gen:hq-crew
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { SEATS, agentBrief, chatApps } from "../src/hqOrg.js";

export function crewMirror() {
  const crew = {};
  for (const s of SEATS) {
    if (s.role === "owner") continue;
    crew[s.id] = { room: s.room, title: s.title, role: s.role, apps: chatApps(s), brief: agentBrief(s) };
  }
  return {
    note: "Generated by `npm run gen:hq-crew` from src/hqOrg.js. Do not edit by hand.",
    crew,
  };
}

export const CREW_JSON = join(dirname(fileURLToPath(import.meta.url)), "..", "functions", "hqCrew.json");
export const render = () => JSON.stringify(crewMirror(), null, 2) + "\n";

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(CREW_JSON, render());
  console.log(`wrote ${CREW_JSON} (${Object.keys(crewMirror().crew).length} seats)`);
}
